# Generated by Django 5.1.1 on 2024-10-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
